// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MandelbrotWindow {
    
    private Gtk.DrawingArea _canvas;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MandelbrotWindow
        this.Name = "MandelbrotWindow";
        this.Title = Mono.Unix.Catalog.GetString("Mandelbrot");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.BorderWidth = ((uint)(12));
        this.DefaultWidth = 300;
        this.DefaultHeight = 300;
        // Container child MandelbrotWindow.Gtk.Container+ContainerChild
        this._canvas = new Gtk.DrawingArea();
        this._canvas.Name = "_canvas";
        this.Add(this._canvas);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
